h=Host("testserver1", "192.168.1.1", "Servers")
h.apply_template("linux")
h.add_test( "Interface", label="eth0", name="eth0", warn=(10,20), crit=(30,40) )
h.add_test("Interface", label="eth1", name="eth1")
h.add_rrd_service("Traffic in eth1", "ineth1", 10, 20)
h.add_tag("Host", "important", 2)
h.add_test("UpTime")
h.add_tag("UpTime", "security", 1)
h.add_trap("test.add_trap", "test.name", "test.label")
h.add_group("Linux servers")
